### ISSUE TITLE
[1.10.2] Crashes on startup

### ISSUE THREAD

**Issue by DeadSix27** [modmuss50/Pong#3]
Version:
Forge: `forge1.10.2-12.18.3.2185`
LiteLoader(_Is it imcompatible?_): `1.10.2-LiteLoader1.10.2`
Pong: `Pong-1.10.2-1.1.0.1-universal.jar`

If you need more info than the stacktrace below (e.g list of mods), tell me.

Stacktrace:
```
Caused by: java.lang.NullPointerException
	at me.modmuss50.pong.PongClassTransformer.transform(PongClassTransformer.java:35) ~[PongClassTransformer.class:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249) ~[forge-1.10.2-12.18.3.2185.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at com.mumfrey.liteloader.transformers.IsolatedClassWriter.getCommonSuperClass(IsolatedClassWriter.java:49) ~[liteloader-1.10.2.jar:1.10.2+unknown-b0.git-unknown]
	at org.objectweb.asm.ClassWriter.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at com.mumfrey.liteloader.transformers.ClassTransformer.writeClass(ClassTransformer.java:58) ~[liteloader-1.10.2.jar:1.10.2+unknown-b0.git-unknown]
	at com.mumfrey.liteloader.client.transformers.MinecraftTransformer.transform(MinecraftTransformer.java:41) ~[liteloader-1.10.2.jar:1.10.2+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
```

**Comment by modmuss50** [comment]
Ok thanks, I will take a look
